### ISSUE TITLE
More tests ported

### ISSUE THREAD

**Issue by azawawi** [azawawi/perl6-file-which#1]
We need to port more tests from File::Which. Namely the following tests:

https://metacpan.org/source/PLICEASE/File-Which-1.21/t/03_simple.t
and
https://metacpan.org/source/PLICEASE/File-Which-1.21/t/02_all.t

**Comment by Altai-man** [comment]
I've looked at these tests and they define a slightly different behavior of the library. As a really quick example: first test stands for returning an undef (or Any in Perl 6) for a null-length strings, while this library just throws an exception.
I can write them, but it will cause changes to the library itself from me. Is it okay?

**Comment by azawawi** [comment]
Go for it :+1:

**Comment by Altai-man** [comment]
Just see the latest PR.

**Comment by azawawi** [comment]
Windows tests fixed in https://github.com/azawawi/perl6-file-which/commit/51a1412052cc9cd990a7ca4686705fefc76736d8. Thanks for your contribution. Please add your name in README :+1:
