### ISSUE TITLE
Fails to install on windows

### ISSUE THREAD

**Issue by sdondley** [azawawi/perl6-file-which#14]
PS C:\Users\sdond> zef install File::Which
===> Searching for: File::Which
===> Updating fez mirror: https://360.zef.pm/
===> Updated fez mirror: https://360.zef.pm/
===> Updating rea mirror: https://raw.githubusercontent.com/Raku/REA/main/META.json
===> Updated rea mirror: https://raw.githubusercontent.com/Raku/REA/main/META.json
===> Testing: File::Which:ver<1.0.1>
[File::Which] # Found perl6 at 'C:\rakubrew\versions\moar-2022.07\install\bin\perl6.EXE'
===> Testing [FAIL]: File::Which:ver<1.0.1>
Aborting due to test failure: File::Which:ver<1.0.1> (use --force-test to override)

**Comment by sdondley** [comment]
PS C:\Users\sdond\Documents\perl6-file-which> prove6 -Ilib t
t\01-which.t ........1/4# Found perl6 at 'C:\rakubrew\versions\moar-2022.07\install\bin\perl6.EXE'
                        t\01-which.t ........ ok
t\02-win32.t ........1/10Type check failed in assignment to $path; expected Str but got Any (Any)
  in block <unit> at t\02-win32.t line 16

# You planned 10 tests, but ran 6
                         t\02-win32.t ........ Dubious, test returned 255
All 10 subtests passed
t\03-export.t .......1/4# Found perl6 at 'C:\rakubrew\versions\moar-2022.07\install\bin\perl6.EXE' using whence
                        t\03-export.t ....... ok
t\04-simple.t .......1/?t\04-simple.t .......2/?                        t\04-simple.t ....... ok
t\05-all.t ..........1/?                        t\05-all.t .......... ok
t\99-author-meta.t ..1/1                        t\99-author-meta.t .. ok
All tests successful.

Test Summary Report
-------------------
t\02-win32.t  (Wstat: 65280 Tests: 6 Failed: 0)
Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 10 tests but ran 6.
Files=6, Tests=27,  6 wallclock secs
Result: FAILED

**Comment by sdondley** [comment]
Issue was the test file 02-win32.t which tested for presence of "wordpad" which is apparently no longer shipped with windows 11.

**Comment by azawawi** [comment]
Merged. Thanks 👍
